#!/usr/bin/env python3
"""Assemble llms-full.txt from the user docs; --check detects stale output."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://danielendler.github.io/datason/"
PAGES = (
    "index.md",
    "getting-started.md",
    "recipes.md",
    "supported-types.md",
    "troubleshooting.md",
    "api.md",
    "configuration.md",
    "security.md",
    "serialization-boundaries.md",
    "agent-data.md",
    "scientific-fidelity.md",
    "plugins.md",
    "langgraph-checkpoints.md",
    "pickle-migration.md",
    "migration.md",
)


def hosted_link(match: re.Match[str]) -> str:
    """Convert a local docs link to its published URL, preserving anchors."""
    target, _, anchor = match.group(2).partition("#")
    slug = "" if target == "index.md" else target.removesuffix(".md") + "/"
    suffix = "#" + anchor if anchor else ""
    return f"[{match.group(1)}]({SITE_URL}{slug}{suffix})"


def render_reference() -> str:
    """Keep explanatory prose and complete snippets from a single source."""
    sections = ["# datason v2 documentation\n\nGenerated by scripts/sync_docs.py; edit docs/*.md instead."]
    for filename in PAGES:
        text = (ROOT / "docs" / filename).read_text(encoding="utf-8")
        text = re.sub(r"\[([^\]]+)\]\(([^)\s]+\.md(?:#[^)\s]+)?)\)", hosted_link, text)
        sections.append(text.rstrip())
    return "\n\n---\n\n".join(sections) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if llms-full.txt needs regeneration")
    args = parser.parse_args()
    target = ROOT / "llms-full.txt"
    expected = render_reference()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit("llms-full.txt is stale; run python scripts/sync_docs.py")
        print("llms-full.txt matches the documentation.")
    else:
        target.write_text(expected, encoding="utf-8")
        print(f"Generated llms-full.txt from {len(PAGES)} guides.")


if __name__ == "__main__":
    main()
